<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
    <title>BigGraphite by criteo</title>

    <link rel="stylesheet" href="stylesheets/styles.css">
    <link rel="stylesheet" href="stylesheets/github-light.css">
    <meta name="viewport" content="width=device-width">
    <!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="wrapper">
      <header>
        <h1>BigGraphite</h1>
        <p>Truly Scalable Simple Time Series Database</p>

        <p class="view"><a href="https://github.com/criteo/biggraphite">View the Project on GitHub <small>criteo/biggraphite</small></a></p>


        <ul>
          <li><a href="https://github.com/criteo/biggraphite/zipball/master">Download <strong>ZIP File</strong></a></li>
          <li><a href="https://github.com/criteo/biggraphite/tarball/master">Download <strong>TAR Ball</strong></a></li>
          <li><a href="https://github.com/criteo/biggraphite">View On <strong>GitHub</strong></a></li>
        </ul>
      </header>
      <section>
